# Generated by Django 5.1.4 on 2024-12-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defended_your_phd_thesis', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('broad_area_of_specialization', models.CharField(max_length=255)),
                ('other_specific_research_area', models.CharField(blank=True, max_length=255, null=True)),
                ('position_applied_for', models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], max_length=50)),
                ('willing_for_visiting_faculty', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('candidate_full_name', models.CharField(max_length=255)),
                ('father_husband', models.CharField(choices=[('FATHER', 'FATHER'), ('HUSBAND', 'HUSBAND')], max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER')], max_length=12)),
                ('category', models.CharField(choices=[('UR', 'UR'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS')], max_length=10)),
                ('nationality', models.CharField(choices=[('INDIAN', 'INDIAN'), ('FOREIGN', 'FOREIGN')], max_length=50)),
            ],
        ),
    ]
