# Generated by Django 5.1.4 on 2024-12-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_thesis_defended', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('specialization', models.CharField(max_length=255)),
                ('research_area', models.CharField(blank=True, max_length=255, null=True)),
                ('position_applied_for', models.CharField(max_length=255)),
                ('visiting_faculty', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('previous_application', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('phd_title', models.TextField()),
                ('phd_defence_date', models.DateField()),
                ('candidate_full_name', models.CharField(max_length=255)),
                ('relative_relation', models.CharField(choices=[('FATHER', 'Father'), ('HUSBAND', 'Husband')], max_length=8)),
                ('relative_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender')], max_length=20)),
                ('category', models.CharField(choices=[('UR', 'UR'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS')], max_length=20)),
                ('category_certificate', models.FileField(upload_to='category_certificates/')),
                ('pwd_category', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('pwd_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pwd_certificate', models.FileField(blank=True, null=True, upload_to='pwd_certificates/')),
                ('nationality', models.CharField(max_length=20)),
                ('pio_oci_none', models.CharField(blank=True, max_length=10, null=True)),
                ('skype_details', models.CharField(blank=True, max_length=255, null=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FacultyRecruitment',
        ),
    ]
