# Generated by Django 5.1.4 on 2024-12-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_applicationdraft_basicdetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicDetails',
        ),
    ]
