# Generated by Django 5.1.4 on 2024-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_basicdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdraft',
            name='candidate_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='category',
            field=models.CharField(blank=True, choices=[('UR', 'UR'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='category_certificate',
            field=models.FileField(blank=True, null=True, upload_to='category_certificates/'),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='phd_defence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='phd_thesis_defended',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='phd_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='position_applied_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='previous_application',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='pwd_category',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='relative_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='relative_relation',
            field=models.CharField(blank=True, choices=[('FATHER', 'Father'), ('HUSBAND', 'Husband')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='visiting_faculty',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
    ]
