# Generated by Django 5.1.4 on 2024-12-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_communicationdetails_user_educationdetails_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_10th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Board/University (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_12th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Board/University (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_graduation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Board/University (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_other1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Board/University (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_other2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Board/University (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_pg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Board/University (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_10th',
            field=models.FileField(blank=True, null=True, upload_to='10th_docs/', verbose_name='10th Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_12th',
            field=models.FileField(blank=True, null=True, upload_to='12th_docs/', verbose_name='12th Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_other1',
            field=models.FileField(blank=True, null=True, upload_to='other_docs_1/', verbose_name='Other Qualification 1 Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_other2',
            field=models.FileField(blank=True, null=True, upload_to='other_docs_2/', verbose_name='Other Qualification 2 Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_10th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_12th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_graduation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_other1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_other2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_pg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Duration (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_10th',
            field=models.CharField(blank=True, choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, null=True, verbose_name='Grade Type (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_12th',
            field=models.CharField(blank=True, choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, null=True, verbose_name='Grade Type (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_graduation',
            field=models.CharField(blank=True, choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, null=True, verbose_name='Grade Type (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_pg',
            field=models.CharField(blank=True, choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, null=True, verbose_name="Grade Type (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='graduation_doc',
            field=models.FileField(blank=True, null=True, upload_to='graduation_docs/', verbose_name='Graduation Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_10th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passing Year (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_12th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passing Year (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_graduation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passing Year (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_other1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passing Year (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_other2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passing Year (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_pg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Passing Year (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='pg_doc',
            field=models.FileField(blank=True, null=True, upload_to='pg_docs/', verbose_name="Master's Degree/DMC"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='qualification_graduation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Graduation Degree'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='qualification_other1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Qualification 1'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='qualification_other2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Qualification 2'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='qualification_pg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Master's Degree"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_10th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subjects (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_12th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subjects (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_graduation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subjects (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_other1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subjects (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_other2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subjects (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_pg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Subjects (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_10th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='%age/CGPA (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_12th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='%age/CGPA (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_graduation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='%age/CGPA (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_other1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='%age/CGPA (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_other2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='%age/CGPA (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_pg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="%age/CGPA (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
