# Generated by Django 5.1.4 on 2024-12-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_basicdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationdetails',
            name='correspondence_address',
            field=models.TextField(blank=True, verbose_name='Correspondence Address'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mobile Number (with country code)'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='permanent_address',
            field=models.TextField(blank=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='discipline_phd',
            field=models.CharField(blank=True, max_length=255, verbose_name='Discipline (PhD)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='end_date_phd',
            field=models.DateField(blank=True, verbose_name='End Date of PhD'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_phd',
            field=models.CharField(blank=True, choices=[('%age', '%age'), ('CGPA', 'CGPA'), ('None Awarded', 'None Awarded')], max_length=50, verbose_name='Grade Type (PhD)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='phd_doc',
            field=models.FileField(blank=True, upload_to='phd_docs/', verbose_name='PhD Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='phd_mode',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('PART-TIME', 'Part-time'), ('DISTANCE', 'Distance')], max_length=50, verbose_name='Mode (PhD)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='start_date_phd',
            field=models.DateField(blank=True, verbose_name='Start Date of PhD'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_phd',
            field=models.CharField(blank=True, max_length=255, verbose_name='%age/CGPA (PhD)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='university_institute_phd',
            field=models.CharField(blank=True, max_length=255, verbose_name='University/Institute (PhD)'),
        ),
    ]
