# Generated by Django 5.1.4 on 2024-12-19 06:50

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_communicationdetails_correspondence_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='category_certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/category_certificates/'),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pwd_certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/pwd_certificates/'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_10th',
            field=models.FileField(blank=True, null=True, upload_to='media/10th_docs/', verbose_name='10th Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_12th',
            field=models.FileField(blank=True, null=True, upload_to='media/12th_docs/', verbose_name='12th Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_other1',
            field=models.FileField(blank=True, null=True, upload_to='media/other_docs_1/', verbose_name='Other Qualification 1 Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_other2',
            field=models.FileField(blank=True, null=True, upload_to='media/other_docs_2/', verbose_name='Other Qualification 2 Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='graduation_doc',
            field=models.FileField(blank=True, null=True, upload_to='media/graduation_docs/', verbose_name='Graduation Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='pg_doc',
            field=models.FileField(blank=True, null=True, upload_to='media/pg_docs/', verbose_name="Master's Degree/DMC"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='phd_doc',
            field=models.FileField(blank=True, upload_to='media/phd_docs/', verbose_name='PhD Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document',
            field=models.FileField(blank=True, help_text='Upload one PDF file only. Max size: 2 MB.', null=True, upload_to='media/experience_documents/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='other_relevant_information',
            field=models.FileField(blank=True, null=True, upload_to='media/relevant_info/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='list_of_consultancy_projects',
            field=models.FileField(blank=True, null=True, upload_to='media/consultancy_projects/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='list_of_sponsored_projects',
            field=models.FileField(blank=True, null=True, upload_to='media/sponsored_projects/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='upload_best_10_publications',
            field=models.FileField(blank=True, null=True, upload_to='media/publications/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='upload_list_of_patents',
            field=models.FileField(blank=True, null=True, upload_to='media/patents/'),
        ),
    ]
