# Generated by Django 5.1.4 on 2024-12-19 07:42

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_basicdetails_category_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetails',
            name='document',
            field=models.FileField(blank=True, help_text='Upload one PDF file only..', null=True, upload_to='media/experience_documents/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
    ]
