# Generated by Django 5.1.4 on 2024-12-19 08:32

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_experiencedetails_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='candidate_full_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='category',
            field=models.CharField(blank=True, choices=[('UR', 'UR'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='category_certificate',
            field=models.FileField(blank=True, default=None, null=True, upload_to='category_certificates/'),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='nationality',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='phd_defence_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='phd_thesis_defended',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='phd_title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pio_oci_none',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='position_applied_for',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='previous_application',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pwd_category',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pwd_certificate',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pwd_certificates/'),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pwd_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='relative_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='relative_relation',
            field=models.CharField(blank=True, choices=[('FATHER', 'Father'), ('HUSBAND', 'Husband')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='research_area',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='skype_details',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='specialization',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='visiting_faculty',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='alternate_contact_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Alternate Contact Number (with country code)'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='alternate_email_address',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Alternate Email Address'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_10th',
            field=models.FileField(blank=True, null=True, upload_to='10th_docs/', verbose_name='10th Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_12th',
            field=models.FileField(blank=True, null=True, upload_to='12th_docs/', verbose_name='12th Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_other1',
            field=models.FileField(blank=True, null=True, upload_to='other_docs_1/', verbose_name='Other Qualification 1 Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_other2',
            field=models.FileField(blank=True, null=True, upload_to='other_docs_2/', verbose_name='Other Qualification 2 Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='graduation_doc',
            field=models.FileField(blank=True, null=True, upload_to='graduation_docs/', verbose_name='Graduation Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='pg_doc',
            field=models.FileField(blank=True, null=True, upload_to='pg_docs/', verbose_name="Master's Degree/DMC"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='phd_doc',
            field=models.FileField(blank=True, upload_to='phd_docs/', verbose_name='PhD Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_documents/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='total_post_phd_experience_months',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='total_post_phd_experience_years',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='academic_or_professional_awards_honours',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='joining_time_required',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='other_relevant_information',
            field=models.FileField(blank=True, default=None, null=True, upload_to='relevant_info/'),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='reference_1',
            field=models.JSONField(blank=True, default=None, help_text="JSON format: [{'name': 'John Doe', 'designation': 'Professor', 'organization': 'XYZ University', 'email': 'john@example.com', 'phone_number': '1234567890'}]", null=True),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='reference_2',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='reference_3',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='book_chapters',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='books_and_monographs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='conferences',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='defended',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='defended_jointly',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='guidance_at_doctoral_level_jointly',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='guidance_at_doctoral_level_singly',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='journals',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='list_of_consultancy_projects',
            field=models.FileField(blank=True, default=None, null=True, upload_to='consultancy_projects/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='list_of_sponsored_projects',
            field=models.FileField(blank=True, default=None, null=True, upload_to='sponsored_projects/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_1',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_3',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_4',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_5',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patents_copyright_obtained',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_1',
            field=models.JSONField(blank=True, default=None, help_text="JSON format: [{'role': 'PI', 'title': 'Title', 'sponsoring_agency': 'Agency', 'status': 'ONGOING', 'amount': 1000}]", null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_2',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_3',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_4',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_5',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_1',
            field=models.JSONField(blank=True, default=None, help_text="JSON format: [{'role': 'PI', 'title': 'Title', 'sponsoring_agency': 'Agency', 'status': 'COMPLETED', 'amount': 5000}]", null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_2',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_3',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_4',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_5',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='publications_in_proceedings_of_seminars_conferences',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='publications_in_refereed_journals',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='thesis_submitted',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='thesis_submitted_jointly',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='total_number_of_patents_only_awarded',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='upload_best_10_publications',
            field=models.FileField(blank=True, default=None, null=True, upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='upload_list_of_patents',
            field=models.FileField(blank=True, default=None, null=True, upload_to='patents/'),
        ),
    ]
