# Generated by Django 5.1.4 on 2024-12-19 12:27

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_basicdetails_candidate_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetails',
            name='document',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
    ]
