# Generated by Django 5.1.4 on 2025-01-02 18:31

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_experiencedetails_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencedetails',
            old_name='document',
            new_name='document_1',
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='document_2',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='document_3',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='document_4',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='document_5',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='document_6',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='document_7',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='document_8',
            field=models.FileField(blank=True, default=None, help_text='Upload one PDF file only..', null=True, upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
    ]
