# Generated by Django 5.1.4 on 2025-01-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_document_experiencedetails_document_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldetails',
            name='joining_time_required',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
