# Generated by Django 5.1.4 on 2025-01-16 19:42

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_generaldetails_joining_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='candidate_full_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='category',
            field=models.CharField(choices=[('UR', 'UR'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='category_certificate',
            field=models.FileField(default=None, upload_to='category_certificates/'),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='nationality',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='phd_defence_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='phd_thesis_defended',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='phd_title',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pio_oci_none',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='position_applied_for',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='previous_application',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pwd_category',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pwd_certificate',
            field=models.FileField(default=None, upload_to='pwd_certificates/'),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='pwd_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='relative_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='relative_relation',
            field=models.CharField(choices=[('FATHER', 'Father'), ('HUSBAND', 'Husband')], default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='research_area',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='skype_details',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='specialization',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='visiting_faculty',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='alternate_contact_number',
            field=models.CharField(default=None, max_length=255, verbose_name='Alternate Contact Number (with country code)'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='alternate_email_address',
            field=models.EmailField(default=None, max_length=254, verbose_name='Alternate Email Address'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='correspondence_address',
            field=models.TextField(verbose_name='Correspondence Address'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='mobile_no',
            field=models.CharField(max_length=255, verbose_name='Mobile Number (with country code)'),
        ),
        migrations.AlterField(
            model_name='communicationdetails',
            name='permanent_address',
            field=models.TextField(verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_10th',
            field=models.CharField(max_length=255, null=True, verbose_name='Board/University (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_12th',
            field=models.CharField(max_length=255, null=True, verbose_name='Board/University (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_graduation',
            field=models.CharField(max_length=255, null=True, verbose_name='Board/University (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_other1',
            field=models.CharField(max_length=255, null=True, verbose_name='Board/University (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_other2',
            field=models.CharField(max_length=255, null=True, verbose_name='Board/University (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='board_university_pg',
            field=models.CharField(max_length=255, null=True, verbose_name="Board/University (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='discipline_phd',
            field=models.CharField(max_length=255, verbose_name='Discipline (PhD)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_10th',
            field=models.FileField(null=True, upload_to='10th_docs/', verbose_name='10th Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_12th',
            field=models.FileField(null=True, upload_to='12th_docs/', verbose_name='12th Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_other1',
            field=models.FileField(null=True, upload_to='other_docs_1/', verbose_name='Other Qualification 1 Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='doc_other2',
            field=models.FileField(null=True, upload_to='other_docs_2/', verbose_name='Other Qualification 2 Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_10th',
            field=models.CharField(max_length=255, null=True, verbose_name='Duration (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_12th',
            field=models.CharField(max_length=255, null=True, verbose_name='Duration (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_graduation',
            field=models.CharField(max_length=255, null=True, verbose_name='Duration (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_other1',
            field=models.CharField(max_length=255, null=True, verbose_name='Duration (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_other2',
            field=models.CharField(max_length=255, null=True, verbose_name='Duration (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='duration_pg',
            field=models.CharField(max_length=255, null=True, verbose_name="Duration (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='end_date_phd',
            field=models.DateField(verbose_name='End Date of PhD'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_10th',
            field=models.CharField(choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, null=True, verbose_name='Grade Type (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_12th',
            field=models.CharField(choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, null=True, verbose_name='Grade Type (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_graduation',
            field=models.CharField(choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, null=True, verbose_name='Grade Type (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_other1',
            field=models.CharField(choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, verbose_name='Grade Type (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_other2',
            field=models.CharField(choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, verbose_name='Grade Type (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_pg',
            field=models.CharField(choices=[('%age', '%age'), ('CGPA', 'CGPA')], max_length=50, null=True, verbose_name="Grade Type (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='grade_type_phd',
            field=models.CharField(choices=[('%age', '%age'), ('CGPA', 'CGPA'), ('None Awarded', 'None Awarded')], max_length=50, verbose_name='Grade Type (PhD)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='graduation_doc',
            field=models.FileField(null=True, upload_to='graduation_docs/', verbose_name='Graduation Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_10th',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='Passing Year (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_12th',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='Passing Year (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_graduation',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='Passing Year (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_other1',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='Passing Year (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_other2',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='Passing Year (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='passing_year_pg',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name="Passing Year (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='pg_doc',
            field=models.FileField(null=True, upload_to='pg_docs/', verbose_name="Master's Degree/DMC"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='phd_doc',
            field=models.FileField(upload_to='phd_docs/', verbose_name='PhD Degree/DMC'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='phd_mode',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('PART-TIME', 'Part-time'), ('DISTANCE', 'Distance')], max_length=50, verbose_name='Mode (PhD)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='qualification_graduation',
            field=models.CharField(max_length=255, null=True, verbose_name='Graduation Degree'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='qualification_other1',
            field=models.CharField(max_length=255, null=True, verbose_name='Other Qualification 1'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='qualification_other2',
            field=models.CharField(max_length=255, null=True, verbose_name='Other Qualification 2'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='qualification_pg',
            field=models.CharField(max_length=255, null=True, verbose_name="Master's Degree"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='start_date_phd',
            field=models.DateField(verbose_name='Start Date of PhD'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_10th',
            field=models.CharField(max_length=255, null=True, verbose_name='Subjects (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_12th',
            field=models.CharField(max_length=255, null=True, verbose_name='Subjects (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_graduation',
            field=models.CharField(max_length=255, null=True, verbose_name='Subjects (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_other1',
            field=models.CharField(max_length=255, null=True, verbose_name='Subjects (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_other2',
            field=models.CharField(max_length=255, null=True, verbose_name='Subjects (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='subjects_pg',
            field=models.CharField(max_length=255, null=True, verbose_name="Subjects (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_10th',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='%age/CGPA (10th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_12th',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='%age/CGPA (12th)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_graduation',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='%age/CGPA (Graduation)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_other1',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='%age/CGPA (Other Qualification 1)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_other2',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='%age/CGPA (Other Qualification 2)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_pg',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name="%age/CGPA (Master's)"),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='total_percentage_cgpa_phd',
            field=models.CharField(default=0, max_length=255, verbose_name='%age/CGPA (PhD)'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='university_institute_phd',
            field=models.CharField(max_length=255, verbose_name='University/Institute (PhD)'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document_1',
            field=models.FileField(default=None, help_text='Upload one PDF file only..', upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document_2',
            field=models.FileField(default=None, help_text='Upload one PDF file only..', upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document_3',
            field=models.FileField(default=None, help_text='Upload one PDF file only..', upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document_4',
            field=models.FileField(default=None, help_text='Upload one PDF file only..', upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document_5',
            field=models.FileField(default=None, help_text='Upload one PDF file only..', upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document_6',
            field=models.FileField(default=None, help_text='Upload one PDF file only..', upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document_7',
            field=models.FileField(default=None, help_text='Upload one PDF file only..', upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='document_8',
            field=models.FileField(default=None, help_text='Upload one PDF file only..', upload_to='experience_docs/', validators=[home.models.validate_pdf_file], verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='total_post_phd_experience_months',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='total_post_phd_experience_years',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='academic_or_professional_awards_honours',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='joining_time_required',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='other_relevant_information',
            field=models.FileField(default=None, upload_to='relevant_info/'),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='reference_1',
            field=models.JSONField(default=None, help_text="JSON format: [{'name': 'John Doe', 'designation': 'Professor', 'organization': 'XYZ University', 'email': 'john@example.com', 'phone_number': '1234567890'}]"),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='reference_2',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='reference_3',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='book_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='books_and_monographs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='conferences',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='defended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='defended_jointly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='guidance_at_doctoral_level_jointly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='guidance_at_doctoral_level_singly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='journals',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='list_of_consultancy_projects',
            field=models.FileField(default=None, upload_to='consultancy_projects/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='list_of_sponsored_projects',
            field=models.FileField(default=None, upload_to='sponsored_projects/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_3',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_4',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patent_5',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patents_copyright_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_1',
            field=models.JSONField(default=None, help_text="JSON format: [{'role': 'PI', 'title': 'Title', 'sponsoring_agency': 'Agency', 'status': 'ONGOING', 'amount': 1000}]"),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_2',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_3',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_4',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_consultancy_project_5',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_1',
            field=models.JSONField(default=None, help_text="JSON format: [{'role': 'PI', 'title': 'Title', 'sponsoring_agency': 'Agency', 'status': 'COMPLETED', 'amount': 5000}]"),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_2',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_3',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_4',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='pi_co_pi_sponsored_project_5',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='publications_in_proceedings_of_seminars_conferences',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='publications_in_refereed_journals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='thesis_submitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='thesis_submitted_jointly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='total_number_of_patents_only_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='upload_best_10_publications',
            field=models.FileField(default=None, upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='upload_list_of_patents',
            field=models.FileField(default=None, upload_to='patents/'),
        ),
    ]
