# Generated by Django 5.1.4 on 2025-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_basicdetails_candidate_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='profilepic',
            field=models.ImageField(default=None, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='total_post_phd_experience_months',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='total_post_phd_experience_years',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='book_chapters',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='books_and_monographs',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='defended',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='defended_jointly',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='guidance_at_doctoral_level_jointly',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='guidance_at_doctoral_level_singly',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='patents_copyright_obtained',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='publications_in_proceedings_of_seminars_conferences',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='publications_in_refereed_journals',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='thesis_submitted',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='thesis_submitted_jointly',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='total_number_of_patents_only_awarded',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
