# Generated by Django 5.1.4 on 2025-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_basicdetails_profilepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
