# Generated by Django 5.1.4 on 2025-03-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_educationdetails_academic_gap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationdetails',
            old_name='gap_duration',
            new_name='academic_gap_duration',
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='gap_from',
            new_name='academic_gap_from',
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='gap_reason',
            new_name='academic_gap_reason',
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='gap_to',
            new_name='academic_gap_to',
        ),
    ]
