# Generated by Django 5.1.4 on 2025-03-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_gap_duration_educationdetails_academic_gap_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationdetails',
            old_name='academic_gap_duration',
            new_name='academic_gap_duration_in_days',
        ),
    ]
